version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=itisha
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 54321:5432
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - 63791:6379
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  postgres-db-volume:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
