version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    restart: always
  
  migrate:
    image: node:18
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npx prisma migrate deploy"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb

  worker:
    build: .
    command: ["node", "dist/jobs/workers/transaction.worker.js"]
    depends_on:
      - redis
    env_file:
      - .env.docker 
    restart: always
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=itisha
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 54321:5432
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - 63791:6379
    networks:
      - app-network
    volumes:
      - redis-data:/data

volumes:
  postgres-db-volume:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
