"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_route_ts_1 = require("./auth.route.ts");
var logger_ts_1 = require("../../../middleware/logger.ts");
var error_ts_1 = require("../../../middleware/error.ts");
var transaction_route_ts_1 = require("./transaction.route.ts");
var limiter_ts_1 = require("../../../middleware/limiter.ts");
var auth_ts_1 = require("../../../middleware/auth.ts");
var docs_route_ts_1 = require("./docs.route.ts");
var apiRouter = express_1.default.Router();
apiRouter.use(logger_ts_1.loggerMiddleware);
apiRouter.use(limiter_ts_1.rateLimiter);
apiRouter.use("/auth", auth_route_ts_1.authRouter);
apiRouter.use("/docs", docs_route_ts_1.docsRouter);
apiRouter.use("/transaction", auth_ts_1.authGuard, transaction_route_ts_1.transactionRouter);
apiRouter.use(error_ts_1.errorHandler);
exports.default = apiRouter;
